logging:
  pattern:
    console: '[%thread] %level - %msg%n'

server:
  port: 10004

spring:
  application:
    name: PAYPAL-SERVICE
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost