logging:
  pattern:
    console: '[%thread] %level - %msg%n'

server:
  port: 10001

spring:
  application:
    name: ORDER-SERVICE
  zipkin:
    base-url: http://localhost:9411/
#removing common properties
#  datasource:
#    url: jdbc:h2:mem:commondb

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
